server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://139.224.226.138:8761/eureka/
  instance:
    hostname: 139.224.226.138
    instance-id: 139.224.226.138:${server.port}
spring:
  application:
    name: nebula-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/JackYanzhe/nebulaits
          searchPaths: /nebulaits-system/nebula-config/**
          username: 
          password: 
      
