server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 139.224.226.138:${server.port}
#服务注册中心实例的主机名
    hostname: 139.224.226.138
  client:
    registerWithEureka: false
    fetchRegistry: false

    