eureka:
  client:
    serviceUrl:
      defaultZone: http://139.224.226.138:8761/eureka/
  instance:
    hostname: 139.224.226.138
    instance-id: 139.224.226.138:${server.port}
server:
  port: 8768
spring:
  application:
    name: nebula-zuul
zuul:
  routes:
    api-a:
      path: /api-dingding/**
      serviceId: nebula-dingding
    api-b:
      path: /api-api/**
      serviceId: nebula-api