eureka:
  client:
    serviceUrl:
      defaultZone: http://47.100.29.15:8761/eureka/
  instance:
    hostname: 47.100.29.15
    instance-id: 47.100.29.15:${server.port}
server:
  port: 8768
spring:
  application:
    name: nebula-zuul
zuul:
  routes:
    api-a:
      path: /api-dingding/**
      serviceId: nebula-dingding
    api-b:
      path: /api-api/**
      serviceId: nebula-api