server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    instance-id: 47.100.29.15:${server.port}
#服务注册中心实例的主机名
    hostname: 47.100.29.15
  client:
    registerWithEureka: false
    fetchRegistry: false

    